version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.4
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
#    shell: /bin/bash --login -o pipefail
    steps:
      - checkout

#Add
      - run: bundle update --bundler
      - run: gem install bundler:1.16.6
#Add

      - run: bundle install
#Add
#      - run: bundler -v
#      - run: gem install fastlane
#Add
      # - run:
      #     name: Fastlane
      #     command: bundle exec fastlane $FASTLANE_LANE
      # - store_artifacts:
      #     path: output
      # - store_test_results:
      #     path: output/scan

  adhoc:
    macos:
      xcode: 13.4
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Game.ipa

  beta:
    macos:
      xcode: 13.4
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Game.ipa

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
      # - adhoc:
      #     filters:
      #       branches:
      #         only: development
      #     requires:
      #       - build-and-test
      #- beta:
          #filters:
            #branches:
              #only: master
          #requires:
            #- build-and-test
